### ISSUE TITLE
Review data needed

### ISSUE THREAD

**Issue by burzt** [AaronElam/favorite-movie-visualizer#8]
Please add a review for your favorite movie or most recently-watched movie in the /backend/reviews/ directory. This data will be aggregated and used for the web application

**Comment by fernandoamz** [comment]
Hello there 👋 , May I add one review?

**Comment by burzt** [comment]
Hi Fernando!
Yes, you may. I'll look into the PR. ~~I need to get the site deployed too...~~ EDIT: The site is deployed at https://hacktobermovielist.herokuapp.com/
